### ISSUE TITLE
Cannot add trakt list

### ISSUE THREAD

**Issue by jeremyy44** [jasongdove/ErsatzTV#1061]
Hi, 
When trying to add a trakt list I get this log error:
```
Refit.ApiException: Response status code does not indicate success: 503 (Service Unavailable).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 313
--- End of stack trace from previous location ---
   at ErsatzTV.Infrastructure.Trakt.TraktApiClient.GetUserList(String user, String list) in /source/ErsatzTV.Infrastructure/Trakt/TraktApiClient.cs:line 33
```
The trakt URL I am using is `https://trakt.tv/users/donxy/lists/marvel-cinematic-universe`
I am running erastztv in a docker container on my ubuntu 22.04 server

**Comment by jeremyy44** [comment]
Forgot to say, but I am on 0.7.0-beta-docker-nvidia

**Comment by jasongdove** [comment]
503 looks like a temporary service issue with trakt itself. Are you able to add the trakt list now?

**Comment by jeremyy44** [comment]
I am yes!
