### ISSUE TITLE
Latest development docker errors and won't use Nvidia GPU

### ISSUE THREAD

**Issue by NotExpectedYet** [jasongdove/ErsatzTV#1151]
Hello, 

I recently updated my docker for the nvidia-development tag and it will no longer use the GPU. I've tested it's still passed through to the container correctly as `nvidia-smi` command gives no errors. 

I get the below on loading the container now. 

```
[10:06:17 WRN] Failed to run health check Unavailable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'mediaItem')
   at ErsatzTV.Core.Extensions.MediaItemExtensions.GetHeadVersion(MediaItem mediaItem) in /source/ErsatzTV.Core/Extensions/MediaItemExtensions.cs:line 18
   at ErsatzTV.Core.Extensions.MediaItemExtensions.GetLocalPath(MediaItem mediaItem, IPlexPathReplacementService plexPathReplacementService, IJellyfinPathReplacementService jellyfinPathReplacementService, IEmbyPathReplacementService embyPathReplacementService, Boolean log) in /source/ErsatzTV.Core/Extensions/MediaItemExtensions.cs:line 28
   at ErsatzTV.Infrastructure.Health.Checks.UnavailableHealthCheck.Check(CancellationToken cancellationToken) in /source/ErsatzTV.Infrastructure/Health/Checks/UnavailableHealthCheck.cs:line 69
   at ErsatzTV.Infrastructure.Health.Checks.UnavailableHealthCheck.Check(CancellationToken cancellationToken) in /source/ErsatzTV.Infrastructure/Health/Checks/UnavailableHealthCheck.cs:line 89
   at LanguageExt.Prelude.<>c__DisplayClass1443_0`1.<<TryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TryAsyncExtensions.Try[T](TryAsync`1 self)
[10:07:02 WRN] Unable to locate episode audio stream selector script; falling back to built-in logic
[10:07:02 WRN] Error detecting NVIDIA GPU capabilities; some hardware accelerated features will be unavailable: 1
[10:07:09 WRN] Unable to locate episode audio stream selector script; falling back to built-in logic
[10:07:10 WRN] Error detecting NVIDIA GPU capabilities; some hardware accelerated features will be unavailable: 1
```

When streaming it just repeats the NVIDIA GPU message again.

**Comment by jasongdove** [comment]
This is the command ETV uses to determine NVIDIA GPU capabilities

```shell
ffmpeg -f lavfi -i nullsrc -c:v h264_nvenc -gpu list -f null -
```

If it's been a while since you've updated, my guess is that there is a new NVIDIA driver requirement. ETV now builds its own ffmpeg images https://github.com/jasongdove/ErsatzTV-ffmpeg and I had to upgrade CUDA to 11.8 to align with the Ubuntu version supported by dotnet 7.

If it's the cuda/driver mismatch, the output from that command will probably have an error about forward compatibility.

**Comment by NotExpectedYet** [comment]
```
[h264_nvenc @ 0x55cfd7dd3580] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

Correct! and thank you very much for the pointer.
