### ISSUE TITLE
[Jellyfin] Error getting jellyfin libraries

### ISSUE THREAD

**Issue by anthonylavado** [jasongdove/ErsatzTV#191]
Version: 0.0.36-prealpha-linux-x64
Operating System: Debian 10, x64
Jellyfin Version: 10.7.5

Steps to Reproduce:
1) Add Jellyfin source (e.g. `http://192.168.0.100:8096`), with API Key

Logs:
(There is an actual user ID, it has been scrubbed from this log.)
```
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 INF] Successfully synchronized jellyfin media sources
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 DBG] Jellyfin admin user id is --------
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 INF] Successfully synchronized Jellyfin admin user id for source 6
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 ERR] Error getting jellyfin libraries
May 19 17:38:53 server.example.com ErsatzTV[24012]: System.NullReferenceException: Object reference not set to an instance of an object.
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at ErsatzTV.Infrastructure.Jellyfin.JellyfinApiClient.Project(JellyfinLibraryResponse response) in /home/runner/work/ErsatzTV/ErsatzTV/ErsatzTV.Infrastructure/Jellyfin/JellyfinApiClient.cs:line 199
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at OptionExtensions.Somes[A](IEnumerable`1 self)+MoveNext()
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
May 19 17:38:53 server.example.com ErsatzTV[24012]:    at ErsatzTV.Infrastructure.Jellyfin.JellyfinApiClient.GetLibraries(String address, String apiKey) in /home/runner/work/ErsatzTV/ErsatzTV/ErsatzTV.Infrastructure/Jellyfin/JellyfinApiClient.cs:line 58
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 WRN] Unable to synchronize libraries from jellyfin server server: Object reference not set to an instance of an object.
May 19 17:38:53 server.example.com ErsatzTV[24012]: [17:38:53 INF] Successfully synchronized Jellyfin libraries for source 6
```

Libaries in Jellyfin, and type:
- Movies, type Movies
- TV Shows, type Shows
- Recordings, type Other
- Music, type Music
- Collections, type Other
- Theatre, type Movies

**Comment by jasongdove** [comment]
This fix is available in [v0.0.37-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.37-prealpha).
