### ISSUE TITLE
"Duration" Playout Mode errors out

### ISSUE THREAD

**Issue by krutburken** [jasongdove/ErsatzTV#345]
This occurs when using a single collection of Movies in the Schedule. I'm trying to get it to schedule between 08:00 and 17:00, and then going offline, but I keep running into this error when generating the Playout:

```
[17:46:42 ERR] Unhandled exception in circuit 'n_u1VmAMZHa1VvOKqEFyujgq76ihmTuWssojSGWDulg'.
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at ErsatzTV.Core.Scheduling.PlayoutBuilder.<>c__DisplayClass8_4.<BuildPlayoutItems>b__19(MediaItem peekMediaItem) in /source/ErsatzTV.Core/Scheduling/PlayoutBuilder.cs:line 371
   at ErsatzTV.Core.Scheduling.PlayoutBuilder.<>c__DisplayClass8_3.<BuildPlayoutItems>b__16(MediaItem mediaItem) in /source/ErsatzTV.Core/Scheduling/PlayoutBuilder.cs:line 353
   at LanguageExt.ClassInstances.MOptionAsync`1.Match(OptionAsync`1 opt, Action`1 Some, Action None)
   at ErsatzTV.Core.Scheduling.PlayoutBuilder.BuildPlayoutItems(Playout playout, DateTimeOffset playoutStart, DateTimeOffset playoutFinish, Boolean rebuild) in /source/ErsatzTV.Core/Scheduling/PlayoutBuilder.cs:line 235
   at ErsatzTV.Core.Scheduling.PlayoutBuilder.BuildPlayoutItems(Playout playout, Boolean rebuild) in /source/ErsatzTV.Core/Scheduling/PlayoutBuilder.cs:line 45
   at ErsatzTV.Application.Playouts.Commands.BuildPlayoutHandler.ApplyUpdateRequest(TvContext dbContext, BuildPlayout request, Playout playout) in /source/ErsatzTV.Application/Playouts/Commands/BuildPlayoutHandler.cs:line 33
   at ErsatzTV.Core.LanguageExtensions.<>c__DisplayClass2_0`2.<<Apply>b__0>d.MoveNext() in /source/ErsatzTV.Core/LanguageExtensions.cs:line 25
--- End of stack trace from previous location ---
   at ErsatzTV.Application.Playouts.Commands.BuildPlayoutHandler.Handle(BuildPlayout request, CancellationToken cancellationToken) in /source/ErsatzTV.Application/Playouts/Commands/BuildPlayoutHandler.cs:line 28
   at ErsatzTV.Application.Playouts.Commands.BuildPlayoutHandler.Handle(BuildPlayout request, CancellationToken cancellationToken) in /source/ErsatzTV.Application/Playouts/Commands/BuildPlayoutHandler.cs:line 28
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at ErsatzTV.Pages.Playouts.RebuildPlayout(PlayoutNameViewModel playout) in /source/ErsatzTV/Pages/Playouts.razor:line 135
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

The settings:
![Screenshot from 2021-08-31 17-50-39](https://user-images.githubusercontent.com/13684929/131536196-abcfdc99-e468-4f3b-b201-72d7dc256c7b.png)

**Comment by jasongdove** [comment]
I think duration here should be `09:00` because that is the length of time that the schedule item will be used in the playout, which will make it from `08:00` to `17:00`. The error is probably because scheduling doesn't like wrapping around midnight (`08:00` + `17:00` = `25:00`), which may be considered a bug but I think it's unrelated to what you're trying to do.

**Comment by krutburken** [comment]
Oh, I feel pretty stupid now. I assumed that I was supposed to input the stop time here, since the controls were the same as when using Start Time.

I haven't tested it yet, but I'm fairly sure it's just pebkac on my part. Thanks.

**Comment by krutburken** [comment]
I just tested this, and unfortunately the error persist. I tried setting a start time of 08:00 and a Duration of 05:00,10:00 and a few other combinations without success

**Comment by jasongdove** [comment]
If you're able to join the discord I might be able to identify this bug more quickly by looking at your ersatztv.sqlite3 database (via DM).

**Comment by krutburken** [comment]
Unfortunately I'm not a discord user, but I can share it via something else (like reddit?)

It's pretty easy to reproduce though:
Use jellyfin as backend,
Sync movie library,
Create normal collection from a bunch of movies,
Create schedule with said collection, using start time and duration (offline tail doesn't matter),
Try to generate playout, get error,
Profit?

**Comment by jasongdove** [comment]
I've definitely tried to reproduce and unfortunately those steps do not work consistently. I believe there's an edge case unaccounted for in your specific data, which is why your database would help. I'm `jasondove` on reddit if you want to dm me a link to your db that way.
