### ISSUE TITLE
Mudelement Errors when loading site on OSX

### ISSUE THREAD

**Issue by bohnje** [jasongdove/ErsatzTV#586]
I am trying to run ErsatzTV for the first time and when loading the site I get a bunch of errors.
`Microsoft.JSInterop.JSException: Could not find 'mudElementRef.getBoundingClientRect' ('mudElementRef' was undefined).
Error: Could not find 'mudElementRef.getBoundingClientRect' ('mudElementRef' was undefined).
    at http://localhost:8409/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (http://localhost:8409/_framework/blazor.server.js:1:465)
    at E (http://localhost:8409/_framework/blazor.server.js:1:2606)
    at http://localhost:8409/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at Tt.beginInvokeJSFromDotNet (http://localhost:8409/_framework/blazor.server.js:1:3475)
    at http://localhost:8409/_framework/blazor.server.js:1:71783
    at Array.forEach (<anonymous>)
    at Tt._invokeClientMethod (http://localhost:8409/_framework/blazor.server.js:1:71769)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at MudBlazor.MudDrawer.UpdateHeight()
   at MudBlazor.MudDrawer.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`

I am running it on Mac OSX version 10.14.6, intel cpu, let me know if there is a way to resolve this. Thanks!

**Comment by jasongdove** [comment]
This is definitely an ongoing problem that I need to track down, but I think you just need to reload without your browsers cache. Ctrl+refresh maybe?

**Comment by jasongdove** [comment]
Looks like an open issue at https://github.com/MudBlazor/MudBlazor/issues/2793

**Comment by bohnje** [comment]
Hmm unfortunately it the `clear cache & hard refresh` didn't solve the issue, but I'm glad to know this sounds like a known issue.  Very excited to (in the near future hopefully) be able to run this!  Thanks for all the hard work on this project, and the fast response!

**Comment by jasongdove** [comment]
The other thing you could try is the develop osx-x64 dmg which is now bundled differently than the most recent release. Artifacts are attached here https://github.com/jasongdove/ErsatzTV/releases/tag/develop

**Comment by bohnje** [comment]
Yeah I had tried the devolp dmg as well, when I run the .app it immediatly closes with:
`Last login: Sat Jan 22 21:13:08 on ttys001
/Applications/ErsatzTV.app/Contents/MacOS/ErsatzTV ; exit;
local:~ Jeremy$ /Applications/ErsatzTV.app/Contents/MacOS/ErsatzTV ; exit;
Killed: 9
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Comment by jasongdove** [comment]
Did you use the proper osx architecture? i.e. x64 not arm64

https://github.com/jasongdove/ErsatzTV/releases/download/develop/ErsatzTV-0.3.7-efef0b0-osx-x64.dmg

**Comment by jasongdove** [comment]
Will also do some testing on my mac, since the dmg files are a pretty new pattern for this project.

**Comment by bohnje** [comment]
Yeah thats the one I used, let me know if you need any more of my systems info

**Comment by jasongdove** [comment]
Please try again with the latest develop release. I believe the issue was fixed here https://github.com/jasongdove/ErsatzTV/commit/14413f62a739c9a9dac29672db82246db446b89e#diff-cb18a99fa3f19997f618f0211573b382bc9f6c2a185f894c9a454720395cd4ffR70

**Comment by jasongdove** [comment]
Closing this for inactivity. Please reopen if this is still an issue.
