### ISSUE TITLE
Plex content is unplayable

### ISSUE THREAD

**Issue by rjl-s** [jasongdove/ErsatzTV#755]
I have just installed the latest beta, and am unable to stream any files, i get the error below - it looks like it is trying to find something in a directory that doesn't exist! (D:\a\)

[10:12:29 INF] Starting HLS session for channel 1
[10:12:30 INF] All content on channel 1 has the same frame rate of null; will not normalize
[10:12:30 INF] HLS segmenter will work ahead for channel 1
[10:12:30 ERR] Error transcoding channel 1
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ErsatzTV.Core.FFmpeg.FFmpegStreamSelector.SelectVideoStream(MediaVersion version) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Core\FFmpeg\FFmpegStreamSelector.cs:line 25
   at ErsatzTV.Core.FFmpeg.FFmpegLibraryProcessService.ForPlayoutItem(String ffmpegPath, String ffprobePath, Boolean saveReports, Channel channel, MediaVersion videoVersion, MediaVersion audioVersion, String videoPath, String audioPath, List`1 subtitles, String preferredAudioLanguage, String preferredSubtitleLanguage, ChannelSubtitleMode subtitleMode, DateTimeOffset start, DateTimeOffset finish, DateTimeOffset now, Option`1 playoutItemWatermark, Option`1 globalWatermark, VaapiDriver vaapiDriver, String vaapiDevice, Boolean hlsRealtime, FillerKind fillerKind, TimeSpan inPoint, TimeSpan outPoint, Int64 ptsOffset, Option`1 targetFramerate) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Core\FFmpeg\FFmpegLibraryProcessService.cs:line 61
   at ErsatzTV.Application.Streaming.GetPlayoutItemProcessByChannelNumberHandler.GetProcess(TvContext dbContext, GetPlayoutItemProcessByChannelNumber request, Channel channel, String ffmpegPath, String ffprobePath, CancellationToken cancellationToken) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Application\Streaming\Queries\GetPlayoutItemProcessByChannelNumberHandler.cs:line 156
   at ErsatzTV.Application.Streaming.FFmpegProcessHandler`1.Handle(T request, CancellationToken cancellationToken) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Application\Streaming\Queries\FFmpegProcessHandler.cs:line 21
   at ErsatzTV.Application.Streaming.FFmpegProcessHandler`1.Handle(T request, CancellationToken cancellationToken) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Application\Streaming\Queries\FFmpegProcessHandler.cs:line 21
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at ErsatzTV.Application.Streaming.HlsSessionWorker.Transcode(Boolean realtime, CancellationToken cancellationToken) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV.Application\Streaming\HlsSessionWorker.cs:line 195

**Comment by jasongdove** [comment]
Thanks for the report!

I think this bug is fixed in the latest develop release. Can you test and confirm?

https://github.com/jasongdove/ErsatzTV/releases/tag/develop

It should automatically re-scan some items from Plex at startup to fix them.

**Comment by jasongdove** [comment]
A fix has been released in https://github.com/jasongdove/ErsatzTV/releases/tag/v0.5.3-beta - please reopen if this doesn't solve your issue.

**Comment by rjl-s** [comment]
Thanks for sorting this, I’m really enjoying the program, keep up the good work!

One more question, how do I set it up so I can access the gui from a different computer ?….
(I’ve added the port to my firewall - it’s running on Windows Server Datacenter 2019)



Thanks,

Roger

**Comment by jasongdove** [comment]
ErsatzTV should bind to all available interfaces, meaning if the firewall allows port `8409` then it should work as expected (i.e. `http://[server-ip-here]:8409/`).

**Comment by rjl-s** [comment]
Hi,

I re-checked the firewall settings, changed the protocol to ‘any’ and it now works !

Any chance you’re working on/going to work on a mobile compatible version of the GUI ?

Thanks

**Comment by jasongdove** [comment]
Yep, a version 2 of the UI is under active development :+1:
